### PR TITLE
Defensive coding against malformed IS

### LINKED ISSUE #499: [Crash] App won't start v0.9.7
Reported from playstore, 6 impacted users

```
java.lang.RuntimeException: Unable to create application im.vector.VectorApp: java.lang.IllegalArgumentException: Invalid URL host: ""
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5533)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6375)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.IllegalArgumentException: Invalid URL host: ""
at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1405)
at okhttp3.HttpUrl.get(HttpUrl.java:916)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:470)
at org.matrix.androidsdk.RestClient.<init>(RestClient.java:169)
at org.matrix.androidsdk.RestClient.<init>(RestClient.java:120)
at org.matrix.androidsdk.rest.client.ThirdPidRestClient.<init>(ThirdPidRestClient.java:60)
at org.matrix.androidsdk.features.identityserver.IdentityServerManager.localSetIdentityServerUrl(IdentityServerManager.kt:278)
at org.matrix.androidsdk.features.identityserver.IdentityServerManager.<init>(IdentityServerManager.kt:69)
at org.matrix.androidsdk.MXSession.<init>(MXSession.java:381)
at org.matrix.androidsdk.MXSession.<init>(MXSession.java:138)
at org.matrix.androidsdk.MXSession$Builder.build(MXSession.java:2753)
at im.vector.Matrix.createSession(Matrix.java:683)
at im.vector.Matrix.createSession(Matrix.java:651)
at im.vector.Matrix.getDefaultSession(Matrix.java:339)
at im.vector.Matrix.addNetworkEventListener(Matrix.java:895)
at im.vector.push.PushManager.<init>(PushManager.java:147)
at im.vector.Matrix.<init>(Matrix.java:207)
at im.vector.Matrix.getInstance(Matrix.java:219)
at im.vector.VectorApp.onCreate(VectorApp.java:235)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5530)
```

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #499
Fixes https://github.com/vector-im/riot-android/issues/3347

### CODE REVIEW

File: matrix-sdk/src/main/java/org/matrix/androidsdk/data/MyUser.java [hunk 1]
```diff
@@ -124,17 +124,20 @@ public void onSuccess(Void info) {
...
-            switch (identifier.medium) {
-                case ThreePid.MEDIUM_EMAIL:
-                    mEmailIdentifiers.add(identifier);
-                    break;
-                case ThreePid.MEDIUM_MSISDN:
-                    mPhoneNumberIdentifiers.add(identifier);
-                    break;
+        List<ThirdPartyIdentifier> identifiers = mDataHandler.getStore().thirdPartyIdentifiers();
+        //NPE reported on playstore
+        if (mDataHandler.getStore() != null) {
```
Comment (bmarty) [inline matrix-sdk/src/main/java/org/matrix/androidsdk/data/MyUser.java]: this is used just above :) the `if`should be before line 129

Comment (BillCarsonFr) [reply matrix-sdk/src/main/java/org/matrix/androidsdk/data/MyUser.java]: oups, done thx
